name: hauberk
environment:
  sdk: '^2.12.0'
dependencies:
  malison: '^0.13.0'
  markdown: any
  path: any
  piecemeal: '^1.0.0'
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  test: any
