name: hauberk
dependencies:
  browser: any
  barback: any
  markdown: any
  malison: any
  piecemeal: any
transformers:
- hauberk/src/markdown_to_html

dependency_overrides:
  piecemeal:
    path:
      ../piecemeal