name: hauberk
sdk: '^2.0.0'
dependencies:
  browser: any
  barback: any
  markdown: any
  malison: '^0.9.0'
  piecemeal: '^0.3.6'
dev_dependencies:
  build_runner: any
  build_web_compilers: any
transformers:
- hauberk/src/markdown_to_html
